# This program meant to store password and other account information into a text file
# this will then be encrypt to prevent others from knowing
# there will be a master key use to decrypt the code
# Reminder!!! this is just a fun little project meant for my personal study
# if anyone come across this i do not recommend you to store any of you information this way/

# to do the encryption you will have to install cryptography module first than import it

import base64
import os
from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives import hashes

# the encryption works is by taking your password alongside a key that you have and randomize it into a nonsense code that will irreversible unless you have both the correct password and key
# here is the example:
# password + key + text encryption = random encryption
# random encryption + password+ key = text encryption
# if any of those is not the same you won't be able to get the correct result


def write_key():
    with open("key.key", "wb") as file:  # wb is stands for write binary the reason we use wb is because the key generated by generate_key() is in bytes which is not a normal string hence we use binary
        file.write(os.urandom(16))


if not os.path.exists("key.key"):
    create_key = input(
        "No encryption key found. Create a new one? (y/n): ").lower()

    if create_key == "y":
        write_key()
    else:
        quit()

# write_key()
# IMPORTANT note, i made a mistake and error when trying to view. this resulted from using the different key.key file and add a new passeord.txt
# in doing so the program cannot recognize the password being decrypt. so when running this code
# always make sure that the key.key and password txt are correct


def load_key():
    with open("key.key", "rb") as file:
        return file.read()


master_code = input("What is the master code? ")
salt = load_key()

kdf = PBKDF2HMAC(
    algorithm=hashes.SHA256(),
    length=32,
    salt=salt,
    iterations=480000,
)

key = base64.urlsafe_b64encode(
    kdf.derive(master_code.encode())
)

fer = Fernet(key)
# add function will add a file and add the password and information into that file


def add():
    name = input('Account name: ')
    password = input('Password: ')


# this line is use to close a file immediately after opening it
# a is the mode of the file. the main modes are (w, r, a)
# w means write which will create a new file or overwrite the already existing file in this case if pasword.txt file already exist using 'w' will clear the entire file and make a new file.
# r means read which will read the content, you can't change anything it literally just a read mode.
# a means append mode which use to add something on the end of your file and create a new file if that file hasn't existed yet
    encrypted = fer.encrypt(
        password.encode()
    ).decode()

    with open('password.txt', 'a') as password_file:
        password_file.write(
            f"{name} | {fer.encrypt(password.encode()).decode()}\n")

# data split is used to make a separation when the program encounter the set requirement
        # in this case everytime it encounter "|" it will make a separation instead of including it in the output


def view():
    with open("password.txt", "r") as password_file:
        for line in password_file:
            user, passw = line.rstrip().split("|")
            user = user.strip()
            passw = passw.strip()
            try:
                password = fer.decrypt(
                    passw.encode()
                ).decode()
                print(f"User: {user}")
                print(f"Password: {password}\n")
            except InvalidToken:
                print("Incorrect master password.")
                return


while True:
    choice = input(
        "Do you want to add a new password or view your existing one (add, view)? press x to quit ").lower()
    if choice == "x":
        break

    if choice == "add":
        add()
    elif choice == "view":
        view()
    else:
        print("Invalid choice")
